### PR TITLE
Changed main character to a snail, added some text

### PR DESCRIPTION
**Pull request by floridop**
Added some content to your story. You are free to ask me to do any change you like before approving! Use this opportunity to experiment.

To complete this task you need to merge my contribution as explained in slides 95-101 keeping in mind that you are the release manager.

### CODE REVIEW

**Review by LucAstrand — CHANGES_REQUESTED** [review]
I like the character change! However, I believe the snail is actually **curious** and is always looking for a new adventure.

**Comment by floridop** [comment]
I made the requested changes! We can keep interacting until you decide to merge.

**Review by LucAstrand — APPROVED** [review]
Thank you for making the requested changes!

**Comment by LucAstrand** [comment]
Approved the changes and merged!

**Comment by floridop** [comment]
I'll close this part of the homework, but if there is something else you're
curious to try and I am available I'll be happy to test.

**Pull request merged**
